name: cd

on:
  push:
    branches:
      - master
      - chore/deploy-python-fn
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-development:
    uses: ./.github/workflows/deploy-step.yml
    with:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_STORAGE_BUCKET_NAME: ${{ vars.GCP_STORAGE_BUCKET_NAME }}
      GCP_STORAGE_FILE_NAME: ${{ vars.GCP_STORAGE_FILE_NAME }}
      GCP_STORAGE_EMBEDDING_FILE_NAME: ${{ vars.GCP_STORAGE_EMBEDDING_FILE_NAME }}
    secrets: inherit
