name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-crawler:
    name: Test crawler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
      - name: Lint
        working-directory: ./packages/crawler
        run: |
          npm run lint
      - name: Run tests
        working-directory: ./packages/crawler
        run: |
          npm test

  test-slack-bot:
    name: Test slack bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ./packages/slack-bot
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        working-directory: ./packages/slack-bot
        run: |
          python test.py

  test-embeddings-creation:
    name: Test embeddings creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ./packages/embeddings-creation
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        working-directory: ./packages/embeddings-creation
        run: |
          python test.py

  automerge:
    name: Merge dependabot's PRs
    needs: [test-crawler, test-slack-bot]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
