name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-crawler:
    name: Test crawler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
      - name: Lint
        run: |
          npm run lint --workspace=crawler
      - name: Run tests
        run: |
          npm test --workspace=crawler

  test-slack-bot:
    name: Test slack bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
      - name: Lint
        working-directory: ./packages/slack-bot
        run: |
          npm run lint
      - name: Run tests
        working-directory: ./packages/slack-bot
        run: |
          npm test

  test-embeddings-creation:
    name: Test embeddings creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
      - name: Lint
        run: |
          npm run lint --workspace=embeddings-creation
      - name: Run tests
        run: |
          npm test --workspace=embeddings-creation

  automerge:
    name: Merge dependabot's PRs
    needs: [test-crawler, test-slack-bot]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
