name: Production deploy

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-production:
    uses: ./.github/workflows/deploy-step.yml
    with:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ vars.GCP_PROJECT_NUMBER }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_STORAGE_BUCKET_NAME: ${{ vars.GCP_STORAGE_BUCKET_NAME }}
      GCP_STORAGE_SCRAPED_FILE_NAME: ${{ vars.GCP_STORAGE_SCRAPED_FILE_NAME }}
      GCP_STORAGE_EMBEDDING_FILE_NAME: ${{ vars.GCP_STORAGE_EMBEDDING_FILE_NAME }}
      GCP_EMBEDDING_SUBSCRIPTION: ${{ vars.GCP_EMBEDDING_SUBSCRIPTION }}
      GCP_EMBEDDING_TOPIC_NAME: ${{ vars.GCP_EMBEDDING_TOPIC_NAME }}
      NETSUITE_ACCOUNT_ID: ${{ vars.NETSUITE_ACCOUNT_ID }}
      NETSUITE_REDIRECT_URI: ${{ vars.NETSUITE_REDIRECT_URI }}
      NESUITE_ALLOWED_ROLE_IDS: ${{ vars.NESUITE_ALLOWED_ROLE_IDS }}
      SLACK_APP_URL: ${{ vars.SLACK_APP_URL }}
    secrets: inherit
